services:
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://dinuka:1234@cluster0.zdovbfd.mongodb.net/uberEats?retryWrites=true&w=majority&appName=Cluster0
      - ORS_API_KEY=5b3ce3597851110001cf6248d96d91fec01e4e8f86ea6331b2c3dcb8

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb+srv://dinuka:1234@cluster0.zdovbfd.mongodb.net/uberEats?retryWrites=true&w=majority&appName=Cluster0

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb+srv://dinuka:1234@cluster0.zdovbfd.mongodb.net/uberEats?retryWrites=true&w=majority&appName=Cluster0

  customer-app:
    build: ./customer-app
    container_name: customer-app
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - payment-service
      - customer-service
